#!/usr/bin/env zsh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/handoff-lib.sh"

usage() {
  cat >&2 <<'EOF'
Usage: swarm_handoff.sh <draft-file>

Draft formats:

type: awake
to: <role>[,<role>...]
priority: NN

type: git_handoff
to: <role>[,<role>...]
priority: NN
task: <short-stable-task-name>
commit: <10-char-commit-abbrev>

type: note
to: <role>[,<role>...]
priority: NN
message: <one line, max 80 chars>
EOF
}

error_report() {
  local draft="$1"
  shift

  echo "HANDOFF INVALID: $draft" >&2
  echo "" >&2
  echo "Errors:" >&2
  local error
  for error in "$@"; do
    echo "- $error" >&2
  done
  echo "" >&2
  usage
}

if [[ $# -ne 1 ]]; then
  usage
  exit 1
fi

DRAFT_FILE="$1"
if [[ ! -f "$DRAFT_FILE" ]]; then
  echo "Draft file not found: $DRAFT_FILE" >&2
  exit 1
fi

SENDER="$(handoff_role_or_default)"
if ! handoff_role_known "$SENDER"; then
  echo "Unknown sender role: $SENDER" >&2
  exit 1
fi

typeset -A HEADERS=()
typeset -a ERRORS=()
typeset -a ORDERED_FIELDS=()
typeset -a RESERVED_FIELDS=(id from role recipient created_at enqueued_at dequeued_at completed_at)
typeset -a ALLOWED_FIELDS=(type to priority task commit message)

line_no=0
body_seen=0
while IFS= read -r line || [[ -n "$line" ]]; do
  line_no=$((line_no + 1))
  if (( body_seen )); then
    [[ -z "$line" ]] || ERRORS+=("Line $line_no: draft handoffs may contain headers only; payloads are generated by swarm_handoff.sh.")
    continue
  fi
  if [[ -z "$line" ]]; then
    body_seen=1
    continue
  fi
  if [[ "$line" != *": "* ]]; then
    ERRORS+=("Line $line_no: expected 'field: value'.")
    continue
  fi
  field="${line%%: *}"
  value="${line#*: }"
  if [[ -z "$field" || -z "$value" ]]; then
    ERRORS+=("Line $line_no: field and value must both be non-empty.")
    continue
  fi
  if (( ${RESERVED_FIELDS[(Ie)$field]} )); then
    ERRORS+=("Line $line_no: header '$field' is reserved and must not be written by agents.")
    continue
  fi
  if (( ! ${ALLOWED_FIELDS[(Ie)$field]} )); then
    ERRORS+=("Line $line_no: unknown header '$field'.")
    continue
  fi
  if [[ -n "${HEADERS[$field]:-}" ]]; then
    ERRORS+=("Line $line_no: duplicate header '$field'.")
    continue
  fi
  HEADERS[$field]="$value"
  ORDERED_FIELDS+=("$field")
done < "$DRAFT_FILE"

TYPE="${HEADERS[type]:-}"
TO="${HEADERS[to]:-}"
PRIORITY="${HEADERS[priority]:-}"
COMMIT="${HEADERS[commit]:-}"
TASK_NAME="${HEADERS[task]:-}"
NOTE_MESSAGE="${HEADERS[message]:-}"

[[ -n "$TYPE" ]] || ERRORS+=("Missing required header 'type'.")
[[ -n "$TO" ]] || ERRORS+=("Missing required header 'to'.")
[[ -n "$PRIORITY" ]] || ERRORS+=("Missing required header 'priority'.")

case "$TYPE" in
  awake|git_handoff|note) ;;
  "") ;;
  *) ERRORS+=("Header 'type' must be one of awake, git_handoff, or note; got '$TYPE'.") ;;
esac

if [[ -n "$PRIORITY" ]] && ! handoff_valid_priority "$PRIORITY"; then
  ERRORS+=("Header 'priority' must be two digits from 00 to 99; got '$PRIORITY'.")
fi

typeset -a RECIPIENTS=()
if [[ -n "$TO" ]]; then
  IFS=',' read -rA RECIPIENTS <<< "$TO"
  typeset -A SEEN_RECIPIENTS=()
  for recipient in "${RECIPIENTS[@]}"; do
    if [[ -z "$recipient" ]]; then
      ERRORS+=("Header 'to' contains an empty recipient.")
      continue
    fi
    if [[ "$recipient" == *"_"* ]]; then
      ERRORS+=("Recipient role '$recipient' is invalid; role names may not contain underscores.")
    fi
    if [[ -n "${SEEN_RECIPIENTS[$recipient]:-}" ]]; then
      ERRORS+=("Duplicate recipient '$recipient'.")
    fi
    SEEN_RECIPIENTS[$recipient]=1
    if ! handoff_role_known "$recipient"; then
      ERRORS+=("Unknown recipient role '$recipient'.")
    fi
  done
fi

for field in "${ORDERED_FIELDS[@]}"; do
  case "$TYPE:$field" in
    awake:type|awake:to|awake:priority) ;;
    git_handoff:type|git_handoff:to|git_handoff:priority|git_handoff:task|git_handoff:commit) ;;
    note:type|note:to|note:priority|note:message) ;;
    *) ERRORS+=("Header '$field' is not allowed for type '$TYPE'.") ;;
  esac
done

CANONICAL_COMMIT=""
if [[ "$TYPE" == "git_handoff" ]]; then
  if [[ -z "$TASK_NAME" ]]; then
    ERRORS+=("Missing required header 'task' for git_handoff.")
  elif [[ "$TASK_NAME" == *$'\n'* ]]; then
    ERRORS+=("Header 'task' must be one line.")
  elif (( ${#TASK_NAME} > 80 )); then
    ERRORS+=("Header 'task' must be no longer than 80 characters; got ${#TASK_NAME}.")
  fi
  if [[ -z "$COMMIT" ]]; then
    ERRORS+=("Missing required header 'commit' for git_handoff.")
  elif [[ "$COMMIT" != [0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F] ]]; then
    ERRORS+=("Header 'commit' must be exactly 10 hexadecimal characters; got '$COMMIT'.")
  else
    matches=("${(@f)$(git rev-parse --disambiguate="$COMMIT" 2>/dev/null || true)}")
    if (( ${#matches[@]} != 1 )); then
      ERRORS+=("Header 'commit' must resolve to exactly one Git object; '$COMMIT' matched ${#matches[@]}.")
    else
      object_type="$(git cat-file -t "${matches[1]}" 2>/dev/null || true)"
      if [[ "$object_type" != "commit" ]]; then
        ERRORS+=("Header 'commit' must resolve to a commit; '$COMMIT' resolves to '$object_type'.")
      else
        CANONICAL_COMMIT="$(git rev-parse --short=10 "${matches[1]}")"
      fi
    fi
  fi
elif [[ -n "$COMMIT" ]]; then
  ERRORS+=("Header 'commit' is only allowed for git_handoff.")
fi

if [[ "$TYPE" != "git_handoff" && -n "$TASK_NAME" ]]; then
  ERRORS+=("Header 'task' is only allowed for git_handoff.")
fi

if [[ "$TYPE" == "note" ]]; then
  if [[ -z "$NOTE_MESSAGE" ]]; then
    ERRORS+=("Missing required header 'message' for note.")
  elif [[ "$NOTE_MESSAGE" == *$'\n'* ]]; then
    ERRORS+=("Header 'message' must be one line.")
  elif (( ${#NOTE_MESSAGE} > 80 )); then
    ERRORS+=("Header 'message' must be no longer than 80 characters; got ${#NOTE_MESSAGE}.")
  fi
elif [[ -n "$NOTE_MESSAGE" ]]; then
  ERRORS+=("Header 'message' is only allowed for note.")
fi

if (( ${#ERRORS[@]} > 0 )); then
  error_report "$DRAFT_FILE" "${ERRORS[@]}"
  exit 2
fi

TIMESTAMP_ID="$(handoff_id_timestamp)"
CREATED_AT="$(handoff_timestamp)"
SEQUENCE="$(handoff_next_sequence)"
ID="${TIMESTAMP_ID}_${SEQUENCE}_from_${SENDER}"
RECIPIENT_SLUG="${(j:_:)RECIPIENTS}"
FILENAME="${PRIORITY}_${TIMESTAMP_ID}_${SEQUENCE}_from_${SENDER}_to_${RECIPIENT_SLUG}.handoff"
OUTBOX_DIR="$(handoff_state_dir)/outbox"
TMP_DIR="$OUTBOX_DIR/tmp"
mkdir -p "$TMP_DIR" "$OUTBOX_DIR" "$(handoff_state_dir)/sent" "$(handoff_state_dir)/failed"

TMP_FILE="$TMP_DIR/$FILENAME.tmp"
OUTBOX_FILE="$OUTBOX_DIR/$FILENAME"

case "$TYPE" in
  awake)
    BODY="awake"
    ;;
  git_handoff)
    BODY=$'Re-read your role and constitution.\n\n'"merge_and_process $SENDER $CANONICAL_COMMIT"
    ;;
  note)
    BODY=$'Re-read your role and constitution.\n\n'"$NOTE_MESSAGE"
    ;;
esac

{
  echo "id: $ID"
  echo "from: $SENDER"
  echo "to: ${(j:,:)RECIPIENTS}"
  echo "priority: $PRIORITY"
  echo "type: $TYPE"
  if [[ "$TYPE" == "git_handoff" ]]; then
    echo "role: $SENDER"
    echo "task: $TASK_NAME"
    echo "commit: $CANONICAL_COMMIT"
  fi
  if [[ "$TYPE" == "note" ]]; then
    echo "message: $NOTE_MESSAGE"
  fi
  echo "created_at: $CREATED_AT"
  echo ""
  printf '%s\n' "$BODY"
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUTBOX_FILE"
echo "HANDOFF QUEUED: $OUTBOX_FILE"
