package handoff

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// ReservedFields must never appear in an operator-authored draft; they are
// filled in by the system as the message moves through the pipeline.
var ReservedFields = map[string]bool{
	"id": true, "from": true, "role": true, "recipient": true,
	"created_at": true, "enqueued_at": true, "dequeued_at": true, "completed_at": true,
}

// AllowedFields is the full set of headers a draft may contain, across
// both message types.
var AllowedFields = map[string]bool{
	"type": true, "to": true, "priority": true,
	"task": true, "commit": true, "message": true,
}

var AllowedTypes = map[string]bool{"git_handoff": true, "note": true}

var (
	priorityRe = regexp.MustCompile(`^[0-9]{2}$`)
	commitRe   = regexp.MustCompile(`^[0-9a-fA-F]{10}$`)
)

// ParsedDraft is the result of parsing a draft file's header block.
type ParsedDraft struct {
	Headers map[string]string
	Ordered []string
	Errors  []string
}

// ParseDraft reads a draft's header block. A draft may contain headers
// only: any non-blank line after the first blank line is an error, since
// payload bodies are generated by WriteDraft, not authored by operators.
func ParseDraft(content string) ParsedDraft {
	headers := map[string]string{}
	var ordered, errs []string
	bodySeen := false

	for i, line := range strings.Split(content, "\n") {
		lineNo := i + 1
		if bodySeen {
			if strings.TrimSpace(line) != "" {
				errs = append(errs, fmt.Sprintf("Line %d: draft handoffs may contain headers only; payloads are generated when the handoff is queued.", lineNo))
			}
			continue
		}
		if strings.TrimSpace(line) == "" {
			bodySeen = true
			continue
		}
		field, value, ok := strings.Cut(line, ": ")
		switch {
		case !ok:
			errs = append(errs, fmt.Sprintf("Line %d: expected 'field: value'.", lineNo))
		case field == "" || value == "":
			errs = append(errs, fmt.Sprintf("Line %d: field and value must both be non-empty.", lineNo))
		case ReservedFields[field]:
			errs = append(errs, fmt.Sprintf("Line %d: header '%s' is reserved and must not be written by agents.", lineNo, field))
		case !AllowedFields[field]:
			errs = append(errs, fmt.Sprintf("Line %d: unknown header '%s'.", lineNo, field))
		case headers[field] != "":
			errs = append(errs, fmt.Sprintf("Line %d: duplicate header '%s'.", lineNo, field))
		default:
			headers[field] = value
			ordered = append(ordered, field)
		}
	}
	return ParsedDraft{Headers: headers, Ordered: ordered, Errors: errs}
}

// RoleChecker reports whether a role name is a configured role.
type RoleChecker func(role string) bool

// CommitResolver resolves a 10-character commit abbreviation to its
// canonical short form, or returns an error describing why it can't
// (ambiguous, not a commit, unknown).
type CommitResolver func(abbrev string) (canonical string, err error)

// ValidationResult is the outcome of validating a parsed draft.
type ValidationResult struct {
	Recipients      []string
	CanonicalCommit string
	Errors          []string
}

// ValidateDraft checks a parsed draft's headers for internal consistency:
// required fields per type, priority/commit format, message/task length
// limits, and recipient well-formedness. roleKnown and resolveCommit may
// be nil to skip those specific checks (useful for offline unit tests).
func ValidateDraft(headers map[string]string, roleKnown RoleChecker, resolveCommit CommitResolver) ValidationResult {
	msgType := headers["type"]
	to := headers["to"]
	priority := headers["priority"]
	commit := headers["commit"]
	taskName := headers["task"]
	noteMessage := headers["message"]

	var errs []string

	recipients, recipientErrs := validateRecipients(to, roleKnown)
	errs = append(errs, recipientErrs...)

	switch {
	case msgType == "":
		errs = append(errs, "Missing required header 'type'.")
	case !AllowedTypes[msgType]:
		errs = append(errs, fmt.Sprintf("Header 'type' must be one of git_handoff or note; got '%s'.", msgType))
	}
	if to == "" {
		errs = append(errs, "Missing required header 'to'.")
	}
	switch {
	case priority == "":
		errs = append(errs, "Missing required header 'priority'.")
	case !priorityRe.MatchString(priority):
		errs = append(errs, fmt.Sprintf("Header 'priority' must be two digits from 00 to 99; got '%s'.", priority))
	}

	var canonicalCommit string
	switch msgType {
	case "git_handoff":
		switch {
		case commit == "":
			errs = append(errs, "Missing required header 'commit' for git_handoff.")
		case !commitRe.MatchString(commit):
			errs = append(errs, fmt.Sprintf("Header 'commit' must be exactly 10 hexadecimal characters; got '%s'.", commit))
		case resolveCommit != nil:
			canonical, err := resolveCommit(commit)
			if err != nil {
				errs = append(errs, err.Error())
			} else {
				canonicalCommit = canonical
			}
		default:
			canonicalCommit = strings.ToLower(commit)
		}
		if taskName == "" {
			errs = append(errs, "Missing required header 'task' for git_handoff.")
		} else if len(taskName) > 80 {
			errs = append(errs, fmt.Sprintf("Header 'task' must be no longer than 80 characters; got %d.", len(taskName)))
		}
		if noteMessage != "" {
			errs = append(errs, "Header 'message' is only allowed for note.")
		}
	case "note":
		switch {
		case noteMessage == "":
			errs = append(errs, "Missing required header 'message' for note.")
		case len(noteMessage) > 80:
			errs = append(errs, fmt.Sprintf("Header 'message' must be no longer than 80 characters; got %d.", len(noteMessage)))
		}
		if commit != "" {
			errs = append(errs, "Header 'commit' is only allowed for git_handoff.")
		}
		if taskName != "" {
			errs = append(errs, "Header 'task' is only allowed for git_handoff.")
		}
	default:
		if commit != "" {
			errs = append(errs, "Header 'commit' is only allowed for git_handoff.")
		}
		if taskName != "" {
			errs = append(errs, "Header 'task' is only allowed for git_handoff.")
		}
		if noteMessage != "" {
			errs = append(errs, "Header 'message' is only allowed for note.")
		}
	}

	return ValidationResult{Recipients: recipients, CanonicalCommit: canonicalCommit, Errors: errs}
}

func validateRecipients(to string, roleKnown RoleChecker) ([]string, []string) {
	if to == "" {
		return nil, nil
	}
	recipients := strings.Split(to, ",")
	seen := map[string]bool{}
	var errs []string
	for _, r := range recipients {
		switch {
		case r == "":
			errs = append(errs, "Header 'to' contains an empty recipient.")
			continue
		case strings.Contains(r, "_"):
			errs = append(errs, fmt.Sprintf("Recipient role '%s' is invalid; role names may not contain underscores.", r))
		case seen[r]:
			errs = append(errs, fmt.Sprintf("Duplicate recipient '%s'.", r))
		}
		seen[r] = true
		if roleKnown != nil && r != "" && !roleKnown(r) {
			errs = append(errs, fmt.Sprintf("Unknown recipient role '%s'.", r))
		}
	}
	return recipients, errs
}

// Body renders a handoff's generated payload for the given message type.
func Body(msgType, sender, canonicalCommit, noteMessage string) string {
	switch msgType {
	case "git_handoff":
		return fmt.Sprintf("Re-read your role and constitution.\n\nmerge_and_process %s %s", sender, canonicalCommit)
	case "note":
		return fmt.Sprintf("Re-read your role and constitution.\n\n%s", noteMessage)
	default:
		return ""
	}
}

// WriteDraft renders a validated draft into the initial outbox file and
// installs it atomically (write to outbox/tmp/, then rename into outbox/).
// handoffsDir is the sender's ".swarmforge/handoffs" directory. Returns the
// path of the installed outbox file.
func WriteDraft(handoffsDir string, headers map[string]string, recipients []string, sender, canonicalCommit string, now time.Time) (string, error) {
	timestampID := IDTimestamp(now)
	seq, err := NextSequence(handoffsDir)
	if err != nil {
		return "", err
	}
	id := ID(timestampID, seq, sender)
	filename := Filename(headers["priority"], timestampID, seq, sender, recipients)
	msgType := headers["type"]
	body := Body(msgType, sender, canonicalCommit, headers["message"])

	lines := []string{
		"id: " + id,
		"from: " + sender,
		"to: " + strings.Join(recipients, ","),
		"priority: " + headers["priority"],
		"type: " + msgType,
	}
	switch msgType {
	case "git_handoff":
		lines = append(lines, "role: "+sender, "task: "+headers["task"], "commit: "+canonicalCommit)
	case "note":
		lines = append(lines, "message: "+headers["message"])
	}
	lines = append(lines, "created_at: "+CreatedAt(now), "", body)
	content := strings.Join(lines, "\n") + "\n"

	outboxDir := filepath.Join(handoffsDir, "outbox")
	tmpDir := filepath.Join(outboxDir, "tmp")
	for _, d := range []string{tmpDir, outboxDir, filepath.Join(handoffsDir, "sent"), filepath.Join(handoffsDir, "failed")} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return "", err
		}
	}
	tmpFile := filepath.Join(tmpDir, filename+".tmp")
	outboxFile := filepath.Join(outboxDir, filename)
	if err := os.WriteFile(tmpFile, []byte(content), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmpFile, outboxFile); err != nil {
		return "", err
	}
	return outboxFile, nil
}
